server:
  port: 8080
spring:
  datasource:
    # 127.0.0.1:8080换成你的服务端IP，端口默认3306，需要的话改自己改。login是数据库名称
    url: jdbc:mysql://49.233.14.150:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: wang
    password: 155620
